### ISSUE TITLE
Automatically add AppImage to GitHub Releases

### ISSUE THREAD

**Issue by philippgille** [philippgille/hello-netcoreapp#9]
Automatically add AppImage (built on Travis CI) to GitHub Releases, which gets created by AppVeyor.

Requires a GitHub Release to be updateable after creation. You can do this manually with the GitHub UI, so it should be possible programmatically as well.

**Comment by philippgille** [comment]
Only possible after #8

**Comment by philippgille** [comment]
For uploading to GitHub Releases, see [Travis CI docs - GitHub Releases Uploading](https://docs.travis-ci.com/user/deployment/releases/). The additions in the `.travis.yml` should look like:

```
deploy:
  provider: releases
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
```
